### ISSUE TITLE
Grid Demos - Behavior Changes Request

### ISSUE THREAD

**Issue by sbozalieva** [IgniteUI/igniteui-js-blocks#451] opened 2017-08-18 08:25 UTC
### Grid with auto generated columns and local data
&nbsp;
1.  After deleting all rows, you can not add a new row.
- [ ] The user should be able to add a row in a empty grid.
&nbsp;
2. "Edit selected cell" edits the cell automatically.
- [x] "Edit selected cell" should have Cancel and Save options.
&nbsp;
### Grid with templated column cells and local observable data source
&nbsp;
1.  When you hide all columns the pager persists. 
- [ ] ~~Since there is no visible data, the pager should hide as well.~~

- [ ] At least one column is always visible.

2.  The Discontinued label is not aligned with the rest of the headers.
- [ ] The Discontinued label should be aligned with the rest of the headers.
&nbsp;
3.  The filter on Discontinued is not relevant.
- [ ] Since the data is true/false, the filter should be a dialog with a radio button True/False.
&nbsp;
4.  When the Sorting icon appears on click it pushes the label to the right.
- [ ] When the Sorting icon appears it should appear on the right, so it won't push the label unnecessary.
&nbsp;
5.  On a third click on the the sorting icon, the icon disappears instead of sorting the column.
- [ ] On a third click on the the sorting icon, the icon should not disappear but sort the column.
 &nbsp;
6.  If you sort on ID, afterwards the other sorting doesn't work.
- [ ] Sorting specific column should not affect sorting on other columns.
&nbsp;
7.  Moving a column doesn't work.
- [ ] Moving a column should move columns
&nbsp;
### Grid with templated cell remote data
&nbsp;
1.   Sorting and filtering doesn't work.
- [ ] Since it is not what we demonstrate, we should probably remove them.
&nbsp;

**Comment by IG-Stanimir-Dimitrov** [comment] 2017-08-18 11:31
@sbozalieva , sell editing already has 'cancel' & 'save' buttons if editing is enabled. You were referring to the first sample which demonstrates editing through the API in which case the input field is not part of the grid UI.

![image](https://user-images.githubusercontent.com/22883855/29456991-c23540f8-8420-11e7-8677-28cc5daa166b.png)

Regarding column hiding, the expected behavior is to match that of igGrid, i.e. at least one column must be unhide-able since there is no business case to have all columns hidden. The pager always stay visible in this scenario.

**Comment by sbozalieva** [comment] 2017-08-18 11:35
@IG-Stanimir-Dimitrov Yes, I was referring to the first demo. Okay, great:)

**Comment by SlavUI** [comment] 2017-11-29 12:02
Closing this issue due to concept change and adjustment already made on the Demos.

**Closed** 2017-11-29 12:02 UTC
