### ISSUE TITLE
grid sample forms squished in IE 11

### ISSUE THREAD

**Issue by jVanZwieten** [IgniteUI/igniteui-js-blocks#472] opened 2017-10-31 20:17 UTC
### Description  
When the Grid sample is viewed in IE, the forms at the top (EG "Add new row") are squished
### Steps to reproduce  

1. open IE 11
2. go to: http://139.59.168.161/grid
3. profit

### Result  
The forms look narrow while IE is full screen.

### Expected result  
The forms are responsive and render with a good aspect ratio allowing for readability, no matter the browser width, but especially when full screen.

### Attachments  
![capture](https://user-images.githubusercontent.com/16783024/32246895-dfb4acc0-be56-11e7-92fa-52e5bcab21a0.PNG)

**Comment by SlavUI** [comment] 2017-11-27 12:07
@simeonoff Hi Simo is there any update on this issue :)

**Comment by kdinev** [comment] 2017-11-27 15:26
The issue is resolved in the product pages: https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid.html

![image](https://user-images.githubusercontent.com/1472513/33274201-16b36d64-d398-11e7-8a30-fea98dd8b40d.png)

**Closed by kdinev** 2017-11-27 15:26 UTC
Labels: status: resolved, styling
